# Site settings
name: "Janessa Suderman"
description: "Wife, mother, author"
url: "https://janessa.ca"

collections:
  books:
    output: true
    permalink: /:collection/:path/
    title: Books

email: janessa@janessa.ca

include:
  - _pages

sass:
  style: compressed
  sass_dir: _includes/sass
  sourcemap: true

# Build settings
markdown: kramdown
permalink: pretty

host: 0.0.0.0
port: 5000
