# Site settings
name: "Janessa"
description: "Wife, mother, author"
url: ""

collections:
  books:
    output: true
    permalink: /:collection/:path/
    title: Books


email: janessa@janessa.ca

include:
  - _pages

sass:
  style: compressed
  sass_dir: _includes/sass
  sourcemap: true

# Build settings
markdown: kramdown
permalink: pretty
